spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: 3h05221021@gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

  datasource:
    url: jdbc:mysql://3.39.169.50:3306/baseballdiary
    username: bbd
    password: 1212
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    user:
      name: abcd
      roles: USER, ADMIN